name: Build ILSpy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - configuration: debug
            solution: ilspy.sln
            channel: zip
          - configuration: release
            solution: ilspy.sln
            channel: zip
          - configuration: release
            solution: ilspy.withpackage.sln
            channel: ci
          - configuration: release
            solution: ilspy.withpackage.sln
            channel: store
    env:
      BuildPlatform: Any CPU
      StagingDirectory: buildartefacts 
    steps:
    - name: Force git to use crlf, otherwise dotnet-format --check fails
      run: git config --global core.autocrlf true
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      with:
       vs-version: '[16.6,16.9)'

    - name: Install dotnet-format
      run: dotnet tool install dotnet-format --global --version 4.1.131201
    - name: Pipelines PS
      run: pwsh .\BuildTools\pipelines-install.ps1

    - name: Restore the application
      run: msbuild ${{ matrix.solution }} /t:Restore /p:Configuration=${{ matrix.configuration }} /p:Platform=$env:BuildPlatform

    - name: Build
      run: msbuild ${{ matrix.solution }} /p:Configuration=${{ matrix.configuration }} /p:Platform=$env:BuildPlatform /p:AppxPackageDir="$env:StagingDirectory\${{ matrix.channel }}\\" 

    - name: Tab check
      run: python BuildTools\tidy.py

    - name: dotnet-format check
      run: dotnet-format --check --verbosity diagnostic ILSpy.sln

